//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément HelloWorldResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebApplication2.ServiceReference1.HelloWorldResponse HelloWorld(WebApplication2.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebApplication2.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément getTitreByIdResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTitreById", ReplyAction="*")]
        WebApplication2.ServiceReference1.getTitreByIdResponse getTitreById(WebApplication2.ServiceReference1.getTitreByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTitreById", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.getTitreByIdResponse> getTitreByIdAsync(WebApplication2.ServiceReference1.getTitreByIdRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément getInscriptionByVolontaireResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInscriptionByVolontaire", ReplyAction="*")]
        WebApplication2.ServiceReference1.getInscriptionByVolontaireResponse getInscriptionByVolontaire(WebApplication2.ServiceReference1.getInscriptionByVolontaireRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInscriptionByVolontaire", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.getInscriptionByVolontaireResponse> getInscriptionByVolontaireAsync(WebApplication2.ServiceReference1.getInscriptionByVolontaireRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebApplication2.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebApplication2.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTitreByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTitreById", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.getTitreByIdRequestBody Body;
        
        public getTitreByIdRequest() {
        }
        
        public getTitreByIdRequest(WebApplication2.ServiceReference1.getTitreByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTitreByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getTitreByIdRequestBody() {
        }
        
        public getTitreByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTitreByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTitreByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.getTitreByIdResponseBody Body;
        
        public getTitreByIdResponse() {
        }
        
        public getTitreByIdResponse(WebApplication2.ServiceReference1.getTitreByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTitreByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTitreByIdResult;
        
        public getTitreByIdResponseBody() {
        }
        
        public getTitreByIdResponseBody(string getTitreByIdResult) {
            this.getTitreByIdResult = getTitreByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInscriptionByVolontaireRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInscriptionByVolontaire", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.getInscriptionByVolontaireRequestBody Body;
        
        public getInscriptionByVolontaireRequest() {
        }
        
        public getInscriptionByVolontaireRequest(WebApplication2.ServiceReference1.getInscriptionByVolontaireRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getInscriptionByVolontaireRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getInscriptionByVolontaireRequestBody() {
        }
        
        public getInscriptionByVolontaireRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInscriptionByVolontaireResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInscriptionByVolontaireResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.getInscriptionByVolontaireResponseBody Body;
        
        public getInscriptionByVolontaireResponse() {
        }
        
        public getInscriptionByVolontaireResponse(WebApplication2.ServiceReference1.getInscriptionByVolontaireResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getInscriptionByVolontaireResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getInscriptionByVolontaireResult;
        
        public getInscriptionByVolontaireResponseBody() {
        }
        
        public getInscriptionByVolontaireResponseBody(string getInscriptionByVolontaireResult) {
            this.getInscriptionByVolontaireResult = getInscriptionByVolontaireResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication2.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication2.ServiceReference1.WebService1Soap>, WebApplication2.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.HelloWorldResponse WebApplication2.ServiceReference1.WebService1Soap.HelloWorld(WebApplication2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebApplication2.ServiceReference1.HelloWorldRequest inValue = new WebApplication2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplication2.ServiceReference1.HelloWorldRequestBody();
            WebApplication2.ServiceReference1.HelloWorldResponse retVal = ((WebApplication2.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.HelloWorldResponse> WebApplication2.ServiceReference1.WebService1Soap.HelloWorldAsync(WebApplication2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebApplication2.ServiceReference1.HelloWorldRequest inValue = new WebApplication2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplication2.ServiceReference1.HelloWorldRequestBody();
            return ((WebApplication2.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.getTitreByIdResponse WebApplication2.ServiceReference1.WebService1Soap.getTitreById(WebApplication2.ServiceReference1.getTitreByIdRequest request) {
            return base.Channel.getTitreById(request);
        }
        
        public string getTitreById(int id) {
            WebApplication2.ServiceReference1.getTitreByIdRequest inValue = new WebApplication2.ServiceReference1.getTitreByIdRequest();
            inValue.Body = new WebApplication2.ServiceReference1.getTitreByIdRequestBody();
            inValue.Body.id = id;
            WebApplication2.ServiceReference1.getTitreByIdResponse retVal = ((WebApplication2.ServiceReference1.WebService1Soap)(this)).getTitreById(inValue);
            return retVal.Body.getTitreByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.getTitreByIdResponse> WebApplication2.ServiceReference1.WebService1Soap.getTitreByIdAsync(WebApplication2.ServiceReference1.getTitreByIdRequest request) {
            return base.Channel.getTitreByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.getTitreByIdResponse> getTitreByIdAsync(int id) {
            WebApplication2.ServiceReference1.getTitreByIdRequest inValue = new WebApplication2.ServiceReference1.getTitreByIdRequest();
            inValue.Body = new WebApplication2.ServiceReference1.getTitreByIdRequestBody();
            inValue.Body.id = id;
            return ((WebApplication2.ServiceReference1.WebService1Soap)(this)).getTitreByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.getInscriptionByVolontaireResponse WebApplication2.ServiceReference1.WebService1Soap.getInscriptionByVolontaire(WebApplication2.ServiceReference1.getInscriptionByVolontaireRequest request) {
            return base.Channel.getInscriptionByVolontaire(request);
        }
        
        public string getInscriptionByVolontaire(int id) {
            WebApplication2.ServiceReference1.getInscriptionByVolontaireRequest inValue = new WebApplication2.ServiceReference1.getInscriptionByVolontaireRequest();
            inValue.Body = new WebApplication2.ServiceReference1.getInscriptionByVolontaireRequestBody();
            inValue.Body.id = id;
            WebApplication2.ServiceReference1.getInscriptionByVolontaireResponse retVal = ((WebApplication2.ServiceReference1.WebService1Soap)(this)).getInscriptionByVolontaire(inValue);
            return retVal.Body.getInscriptionByVolontaireResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.getInscriptionByVolontaireResponse> WebApplication2.ServiceReference1.WebService1Soap.getInscriptionByVolontaireAsync(WebApplication2.ServiceReference1.getInscriptionByVolontaireRequest request) {
            return base.Channel.getInscriptionByVolontaireAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.getInscriptionByVolontaireResponse> getInscriptionByVolontaireAsync(int id) {
            WebApplication2.ServiceReference1.getInscriptionByVolontaireRequest inValue = new WebApplication2.ServiceReference1.getInscriptionByVolontaireRequest();
            inValue.Body = new WebApplication2.ServiceReference1.getInscriptionByVolontaireRequestBody();
            inValue.Body.id = id;
            return ((WebApplication2.ServiceReference1.WebService1Soap)(this)).getInscriptionByVolontaireAsync(inValue);
        }
    }
}
